In [11]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P
0  0  0  0  0  0  0  1  1  1  0  0  0  0  0  0  2
1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0
2  0  0  0  1  1  1  0  0  0  0  0  0  0  0  0  1
3  0  0  0  0  0  0  0  0  0  1  1  1  0  0  0  3
4  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  4

In [5]:
y = df['P'].values

In [7]:
y

array([2, 0, 1, 3, 4, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 0, 0,
       0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [8]:
X = df[['A', 'B','C', 'D', 'E', 'F', 'G', 'H','I', 'J', 'K']] .values

In [10]:
X[0:5]

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
k = 4  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='uniform')

In [14]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([3, 0, 4, 0, 4])

In [15]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.8928571428571429
Test set Accuracy:  0.8571428571428571


In [17]:
df.shape

(35, 16)